# Generated by Django 4.0.4 on 2022-05-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
    ]
